### PR TITLE
Update catalog item to follow the specification v2

### PR DESCRIPTION
**Pull request by tbouron**

### CODE REVIEW

**Comment by sjcorbett** [comment]
@tbouron Thanks.

**Comment by tbouron** [comment]
No problem @sjcorbett .

BTW, I noticed that your `catalog.bom` does not include the library part, [same as what Richard did for his blueprint](https://github.com/rdowner/brooklyn-temperature-device/blob/master/catalog.bom#L25-L26). I'm afraid the blueprint won't work without it.

**Comment by sjcorbett** [comment]
I think that is one for general discussion - at the moment this project is not published anywhere and the onus is on the user to build and do it themselves, whether by publishing an artefact or by putting the right classes on Brooklyn's classpath.

**Comment by tbouron** [comment]
Hum, I see. I just wanted to point it out :)

**Pull request merged**
